// <auto-generated />
using System;
using AzureAdB2BApi.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzureAdB2BApi.Migrations
{
    [DbContext(typeof(InvitationsDbContext))]
    [Migration("20240424144310_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AzureAdB2BApi.Models.UserInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DelegatedUserManagementRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ExpiresTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InvitationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserInvitations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("24ba9736-b7ae-411c-a516-f1f8cff0d251"),
                            CreatedBy = "system",
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 4, 24, 10, 43, 10, 314, DateTimeKind.Unspecified).AddTicks(8987), new TimeSpan(0, -4, 0, 0, 0)),
                            CustomerId = new Guid("68f731f3-5cda-4b3d-97e6-72439842d522"),
                            DelegatedUserManagementRole = "CompanyAdmin",
                            ExpiresTime = new DateTimeOffset(new DateTime(2024, 4, 24, 10, 43, 10, 314, DateTimeKind.Unspecified).AddTicks(9034), new TimeSpan(0, -4, 0, 0, 0)),
                            InvitationCode = "HP4JXHMTCJ"
                        },
                        new
                        {
                            Id = new Guid("9911db18-e8ba-4b83-8c4f-2676e8fc8cfb"),
                            CreatedBy = "system",
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 4, 24, 10, 43, 10, 314, DateTimeKind.Unspecified).AddTicks(9043), new TimeSpan(0, -4, 0, 0, 0)),
                            CustomerId = new Guid("83ceec59-d9a5-4031-8347-fc4a1d516147"),
                            DelegatedUserManagementRole = "CompanyAdmin",
                            ExpiresTime = new DateTimeOffset(new DateTime(2024, 4, 24, 10, 43, 10, 314, DateTimeKind.Unspecified).AddTicks(9045), new TimeSpan(0, -4, 0, 0, 0)),
                            InvitationCode = "QJHM87VD49"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
